[package]
name = "rust-samples"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
indicatif = { version = "0.17.7", features = ["rayon"] }
rayon = "1.8.1"
thiserror = "1.0.50"
